import {
  User,
  Client,
  Task,
  TaskItem,
  TaskDocument,
  ActivityLog,
  Role,
  TaskStatus,
  Priority,
  EntityType,
  DashboardMetrics,
  ComplianceDeadline,
  ServicePage,
  DocumentRequest,
  MessageThread,
  Message,
} from './types';

// ============================================================
// Users
// ============================================================

export const mockUsers: User[] = [
  {
    id: 'usr_admin_01',
    name: 'CA Rajesh Sharma',
    email: 'rajesh@sharmaassociates.in',
    phone: '+91 98765 43210',
    role: Role.ADMIN,
    isActive: true,
    createdAt: '2020-04-01T00:00:00Z',
    updatedAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'usr_worker_01',
    name: 'Priya Mehta',
    email: 'priya@sharmaassociates.in',
    phone: '+91 87654 32109',
    role: Role.WORKER,
    isActive: true,
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2025-09-18T10:00:00Z',
  },
  {
    id: 'usr_worker_02',
    name: 'Amit Verma',
    email: 'amit@sharmaassociates.in',
    phone: '+91 76543 21098',
    role: Role.WORKER,
    isActive: true,
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2025-09-19T10:00:00Z',
  },
  {
    id: 'usr_worker_03',
    name: 'Sneha Patel',
    email: 'sneha@sharmaassociates.in',
    phone: '+91 65432 10987',
    role: Role.WORKER,
    isActive: true,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-09-17T10:00:00Z',
  },
  {
    id: 'usr_worker_04',
    name: 'Rohan Gupta',
    email: 'rohan@sharmaassociates.in',
    phone: '+91 54321 09876',
    role: Role.WORKER,
    isActive: false,
    createdAt: '2022-08-20T00:00:00Z',
    updatedAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'usr_client_01',
    name: 'Vikram Singh',
    email: 'vikram@technovate.in',
    phone: '+91 99887 76655',
    role: Role.CLIENT,
    isActive: true,
    createdAt: '2022-04-10T00:00:00Z',
    updatedAt: '2025-09-15T10:00:00Z',
  },
  {
    id: 'usr_client_02',
    name: 'Ananya Reddy',
    email: 'ananya@greenlabel.in',
    phone: '+91 88776 65544',
    role: Role.CLIENT,
    isActive: true,
    createdAt: '2023-07-20T00:00:00Z',
    updatedAt: '2025-09-14T10:00:00Z',
  },
  {
    id: 'usr_client_03',
    name: 'Suresh Agarwal',
    email: 'suresh.agarwal@gmail.com',
    phone: '+91 77665 54433',
    role: Role.CLIENT,
    isActive: true,
    createdAt: '2021-01-05T00:00:00Z',
    updatedAt: '2025-09-16T10:00:00Z',
  },
];

// ============================================================
// Clients
// ============================================================

export const mockClients: Client[] = [
  {
    id: 'cli_01',
    userId: 'usr_client_01',
    user: mockUsers.find((u) => u.id === 'usr_client_01'),
    entityName: 'Technovate Solutions Pvt. Ltd.',
    entityType: EntityType.PRIVATE_LIMITED,
    pan: 'AABCT1234A',
    gstin: '27AABCT1234A1Z5',
    tan: 'MUMT12345A',
    cin: 'U72200MH2018PTC123456',
    directorDins: ['08765432', '09876543'],
    authorizedSignatory: 'Vikram Singh',
    contactPerson: 'Vikram Singh',
    contactEmail: 'vikram@technovate.in',
    contactPhone: '+91 99887 76655',
    assignedWorkerId: 'usr_worker_01',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_01'),
    createdAt: '2022-04-10T00:00:00Z',
  },
  {
    id: 'cli_02',
    userId: 'usr_client_02',
    user: mockUsers.find((u) => u.id === 'usr_client_02'),
    entityName: 'GreenLabel Organics LLP',
    entityType: EntityType.LLP,
    pan: 'AADGG5678B',
    gstin: '36AADGG5678B1Z3',
    tan: 'HYDT67890B',
    cin: 'AAT-9876',
    contactPerson: 'Ananya Reddy',
    contactEmail: 'ananya@greenlabel.in',
    contactPhone: '+91 88776 65544',
    assignedWorkerId: 'usr_worker_02',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_02'),
    createdAt: '2023-07-20T00:00:00Z',
  },
  {
    id: 'cli_03',
    userId: 'usr_client_03',
    user: mockUsers.find((u) => u.id === 'usr_client_03'),
    entityName: 'Suresh Agarwal (Individual)',
    entityType: EntityType.INDIVIDUAL,
    pan: 'ABCPA1234C',
    contactPerson: 'Suresh Agarwal',
    contactEmail: 'suresh.agarwal@gmail.com',
    contactPhone: '+91 77665 54433',
    assignedWorkerId: 'usr_worker_01',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_01'),
    createdAt: '2021-01-05T00:00:00Z',
  },
  {
    id: 'cli_04',
    entityName: 'Kapoor Traders',
    entityType: EntityType.PROPRIETORSHIP,
    pan: 'BZKPK9876D',
    gstin: '07BZKPK9876D1Z2',
    contactPerson: 'Ramesh Kapoor',
    contactEmail: 'ramesh@kapoortraders.com',
    contactPhone: '+91 98112 34567',
    assignedWorkerId: 'usr_worker_03',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_03'),
    createdAt: '2023-03-15T00:00:00Z',
  },
  {
    id: 'cli_05',
    entityName: 'Horizon Infra Projects Pvt. Ltd.',
    entityType: EntityType.PRIVATE_LIMITED,
    pan: 'AABCH7654E',
    gstin: '27AABCH7654E1Z8',
    tan: 'MUMH54321E',
    cin: 'U45200MH2019PTC789012',
    directorDins: ['07654321'],
    authorizedSignatory: 'Deepak Joshi',
    contactPerson: 'Deepak Joshi',
    contactEmail: 'deepak@horizoninfra.in',
    contactPhone: '+91 98210 56789',
    assignedWorkerId: 'usr_worker_01',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_01'),
    createdAt: '2022-11-01T00:00:00Z',
  },
  {
    id: 'cli_06',
    entityName: 'NovaByte Technologies LLP',
    entityType: EntityType.LLP,
    pan: 'AAFN4321F',
    gstin: '29AAFN4321F1Z6',
    tan: 'BLRN98765F',
    cin: 'AAR-5432',
    contactPerson: 'Kiran Rao',
    contactEmail: 'kiran@novabyte.co',
    contactPhone: '+91 80345 67890',
    assignedWorkerId: 'usr_worker_02',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_02'),
    createdAt: '2024-02-14T00:00:00Z',
  },
  {
    id: 'cli_07',
    entityName: 'Malhotra & Sons Partnership',
    entityType: EntityType.PARTNERSHIP,
    pan: 'AACFM8765G',
    gstin: '06AACFM8765G1Z4',
    contactPerson: 'Anil Malhotra',
    contactEmail: 'anil@malhotrasions.com',
    contactPhone: '+91 98765 11223',
    assignedWorkerId: 'usr_worker_03',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_03'),
    createdAt: '2021-08-20T00:00:00Z',
  },
  {
    id: 'cli_08',
    entityName: 'Meera Iyer (Individual)',
    entityType: EntityType.INDIVIDUAL,
    pan: 'ABCPI5678H',
    contactPerson: 'Meera Iyer',
    contactEmail: 'meera.iyer@outlook.com',
    contactPhone: '+91 90001 23456',
    assignedWorkerId: 'usr_worker_02',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_02'),
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'cli_09',
    entityName: 'UrbanNest Realty Pvt. Ltd.',
    entityType: EntityType.PRIVATE_LIMITED,
    pan: 'AABCU2345I',
    gstin: '27AABCU2345I1Z1',
    tan: 'MUMU67890I',
    cin: 'U70100MH2020PTC345678',
    directorDins: ['06543210', '08765401'],
    authorizedSignatory: 'Neha Bhatia',
    contactPerson: 'Neha Bhatia',
    contactEmail: 'neha@urbannest.in',
    contactPhone: '+91 98765 09876',
    assignedWorkerId: 'usr_worker_01',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_01'),
    createdAt: '2023-09-10T00:00:00Z',
  },
  {
    id: 'cli_10',
    entityName: 'FreshBite Foods',
    entityType: EntityType.PROPRIETORSHIP,
    pan: 'CDEPF3456J',
    gstin: '27CDEPF3456J1Z9',
    contactPerson: 'Pankaj Deshmukh',
    contactEmail: 'pankaj@freshbite.in',
    contactPhone: '+91 88001 22334',
    assignedWorkerId: 'usr_worker_03',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_03'),
    createdAt: '2024-04-05T00:00:00Z',
  },
  {
    id: 'cli_11',
    entityName: 'Pinnacle Consulting Pvt. Ltd.',
    entityType: EntityType.PRIVATE_LIMITED,
    pan: 'AABCP6789K',
    gstin: '27AABCP6789K1Z7',
    tan: 'MUMP12345K',
    cin: 'U74999MH2021PTC901234',
    contactPerson: 'Siddharth Nair',
    contactEmail: 'sid@pinnacleconsulting.in',
    contactPhone: '+91 98234 56780',
    createdAt: '2024-08-15T00:00:00Z',
  },
  {
    id: 'cli_12',
    entityName: 'Arvind Textiles LLP',
    entityType: EntityType.LLP,
    pan: 'AAFA8901L',
    gstin: '24AAFA8901L1Z5',
    tan: 'AHMA45678L',
    contactPerson: 'Arvind Shah',
    contactEmail: 'arvind@arvindtextiles.co.in',
    contactPhone: '+91 79123 45678',
    assignedWorkerId: 'usr_worker_02',
    assignedWorker: mockUsers.find((u) => u.id === 'usr_worker_02'),
    createdAt: '2022-06-30T00:00:00Z',
  },
];

// ============================================================
// Task Checklists
// ============================================================

const gstFilingChecklist: Omit<TaskItem, 'id' | 'taskId'>[] = [
  { label: 'Sales register reconciled with GSTR-1', isCompleted: false },
  { label: 'Purchase register reconciled with GSTR-2B', isCompleted: false },
  { label: 'ITC mismatch resolved', isCompleted: false },
  { label: 'GSTR-3B liability computed', isCompleted: false },
  { label: 'Challan generated and paid', isCompleted: false },
  { label: 'Return filed on GST portal', isCompleted: false },
  { label: 'Filing receipt downloaded', isCompleted: false },
];

const itrFilingChecklist: Omit<TaskItem, 'id' | 'taskId'>[] = [
  { label: 'Form 26AS / AIS reconciled', isCompleted: false },
  { label: 'Capital gains statement collected', isCompleted: false },
  { label: 'Deduction proofs verified (80C/80D)', isCompleted: false },
  { label: 'Tax computation prepared', isCompleted: false },
  { label: 'Self-assessment tax paid', isCompleted: false },
  { label: 'ITR filed on Income Tax portal', isCompleted: false },
  { label: 'ITR-V submitted / e-verified', isCompleted: false },
];

const auditChecklist: Omit<TaskItem, 'id' | 'taskId'>[] = [
  { label: 'Trial balance received and verified', isCompleted: false },
  { label: 'Bank reconciliation completed', isCompleted: false },
  { label: 'Fixed asset register reviewed', isCompleted: false },
  { label: 'Debtors/creditors confirmation obtained', isCompleted: false },
  { label: 'Tax audit report (3CA/3CD) drafted', isCompleted: false },
  { label: 'Partner review completed', isCompleted: false },
  { label: 'Audit report signed and filed', isCompleted: false },
];

function makeChecklist(
  template: Omit<TaskItem, 'id' | 'taskId'>[],
  taskId: string,
  completedCount: number
): TaskItem[] {
  return template.map((item, idx) => ({
    ...item,
    id: `ti_${taskId}_${idx + 1}`,
    taskId,
    isCompleted: idx < completedCount,
  }));
}

// ============================================================
// Tasks
// ============================================================

export const mockTasks: Task[] = [
  {
    id: 'task_01',
    title: 'GSTR-3B Filing — September 2025',
    description: 'Monthly GST return filing for Technovate Solutions for the period September 2025.',
    clientId: 'cli_01',
    client: mockClients.find((c) => c.id === 'cli_01'),
    assignedToId: 'usr_worker_01',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_01'),
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    financialYear: '2025-2026',
    dueDate: '2025-10-20T23:59:59Z',
    checklist: makeChecklist(gstFilingChecklist, 'task_01', 3),
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-09-22T14:30:00Z',
  },
  {
    id: 'task_02',
    title: 'ITR Filing — AY 2025-26',
    description: 'Individual income tax return filing for Suresh Agarwal for Assessment Year 2025-26.',
    clientId: 'cli_03',
    client: mockClients.find((c) => c.id === 'cli_03'),
    assignedToId: 'usr_worker_01',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_01'),
    status: TaskStatus.UNDER_REVIEW,
    priority: Priority.URGENT,
    financialYear: '2024-2025',
    dueDate: '2025-09-30T23:59:59Z',
    checklist: makeChecklist(itrFilingChecklist, 'task_02', 6),
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-09-20T16:00:00Z',
  },
  {
    id: 'task_03',
    title: 'Statutory Audit — FY 2024-25',
    description: 'Annual statutory audit for Horizon Infra Projects Pvt. Ltd.',
    clientId: 'cli_05',
    client: mockClients.find((c) => c.id === 'cli_05'),
    assignedToId: 'usr_worker_01',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_01'),
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    financialYear: '2024-2025',
    dueDate: '2025-09-30T23:59:59Z',
    checklist: makeChecklist(auditChecklist, 'task_03', 2),
    createdAt: '2025-07-15T10:00:00Z',
    updatedAt: '2025-09-21T11:00:00Z',
  },
  {
    id: 'task_04',
    title: 'GSTR-1 Filing — September 2025',
    description: 'Outward supply return filing for GreenLabel Organics LLP.',
    clientId: 'cli_02',
    client: mockClients.find((c) => c.id === 'cli_02'),
    assignedToId: 'usr_worker_02',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_02'),
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    financialYear: '2025-2026',
    dueDate: '2025-10-11T23:59:59Z',
    checklist: makeChecklist(gstFilingChecklist, 'task_04', 0),
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'task_05',
    title: 'TDS Return — Q2 FY 2025-26',
    description: 'Quarterly TDS return (Form 24Q/26Q) for Kapoor Traders.',
    clientId: 'cli_04',
    client: mockClients.find((c) => c.id === 'cli_04'),
    assignedToId: 'usr_worker_03',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_03'),
    status: TaskStatus.WAITING_ON_CLIENT,
    priority: Priority.MEDIUM,
    financialYear: '2025-2026',
    dueDate: '2025-10-31T23:59:59Z',
    checklist: [
      { id: 'ti_task_05_1', taskId: 'task_05', label: 'Salary details collected', isCompleted: true },
      { id: 'ti_task_05_2', taskId: 'task_05', label: 'Vendor payment details received', isCompleted: false },
      { id: 'ti_task_05_3', taskId: 'task_05', label: 'TDS computation verified', isCompleted: false },
      { id: 'ti_task_05_4', taskId: 'task_05', label: 'Return filed on TRACES', isCompleted: false },
    ],
    createdAt: '2025-09-10T10:00:00Z',
    updatedAt: '2025-09-18T09:00:00Z',
  },
  {
    id: 'task_06',
    title: 'Company Annual Filing — FY 2024-25',
    description: 'ROC annual return (MGT-7) and AOC-4 filing for UrbanNest Realty Pvt. Ltd.',
    clientId: 'cli_09',
    client: mockClients.find((c) => c.id === 'cli_09'),
    assignedToId: 'usr_worker_01',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_01'),
    status: TaskStatus.TODO,
    priority: Priority.LOW,
    financialYear: '2024-2025',
    dueDate: '2025-11-29T23:59:59Z',
    checklist: [
      { id: 'ti_task_06_1', taskId: 'task_06', label: 'Board resolution obtained', isCompleted: false },
      { id: 'ti_task_06_2', taskId: 'task_06', label: 'Financial statements finalized', isCompleted: false },
      { id: 'ti_task_06_3', taskId: 'task_06', label: 'MGT-7 form prepared', isCompleted: false },
      { id: 'ti_task_06_4', taskId: 'task_06', label: 'AOC-4 form prepared', isCompleted: false },
      { id: 'ti_task_06_5', taskId: 'task_06', label: 'Filed on MCA portal', isCompleted: false },
    ],
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-09-01T10:00:00Z',
  },
  {
    id: 'task_07',
    title: 'GSTR-3B Filing — September 2025',
    description: 'Monthly GST return for NovaByte Technologies LLP.',
    clientId: 'cli_06',
    client: mockClients.find((c) => c.id === 'cli_06'),
    assignedToId: 'usr_worker_02',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_02'),
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    financialYear: '2025-2026',
    dueDate: '2025-10-20T23:59:59Z',
    checklist: makeChecklist(gstFilingChecklist, 'task_07', 4),
    createdAt: '2025-09-16T10:00:00Z',
    updatedAt: '2025-09-22T10:00:00Z',
  },
  {
    id: 'task_08',
    title: 'ITR Filing — AY 2025-26',
    description: 'Partnership firm ITR-5 filing for Malhotra & Sons.',
    clientId: 'cli_07',
    client: mockClients.find((c) => c.id === 'cli_07'),
    assignedToId: 'usr_worker_03',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_03'),
    status: TaskStatus.COMPLETED,
    priority: Priority.HIGH,
    financialYear: '2024-2025',
    dueDate: '2025-07-31T23:59:59Z',
    completedAt: '2025-07-28T15:30:00Z',
    checklist: makeChecklist(itrFilingChecklist, 'task_08', 7),
    createdAt: '2025-05-15T10:00:00Z',
    updatedAt: '2025-07-28T15:30:00Z',
  },
  {
    id: 'task_09',
    title: 'GSTR-3B Filing — September 2025',
    description: 'Monthly GST return for FreshBite Foods.',
    clientId: 'cli_10',
    client: mockClients.find((c) => c.id === 'cli_10'),
    assignedToId: 'usr_worker_03',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_03'),
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    financialYear: '2025-2026',
    dueDate: '2025-10-20T23:59:59Z',
    checklist: makeChecklist(gstFilingChecklist, 'task_09', 0),
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'task_10',
    title: 'LLP Annual Return — FY 2024-25',
    description: 'Form 11 and Statement of Accounts for Arvind Textiles LLP.',
    clientId: 'cli_12',
    client: mockClients.find((c) => c.id === 'cli_12'),
    assignedToId: 'usr_worker_02',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_02'),
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.MEDIUM,
    financialYear: '2024-2025',
    dueDate: '2025-10-30T23:59:59Z',
    checklist: [
      { id: 'ti_task_10_1', taskId: 'task_10', label: 'Partners capital reconciled', isCompleted: true },
      { id: 'ti_task_10_2', taskId: 'task_10', label: 'Statement of Accounts finalized', isCompleted: true },
      { id: 'ti_task_10_3', taskId: 'task_10', label: 'Form 11 prepared', isCompleted: false },
      { id: 'ti_task_10_4', taskId: 'task_10', label: 'Filed on MCA portal', isCompleted: false },
    ],
    createdAt: '2025-08-15T10:00:00Z',
    updatedAt: '2025-09-19T10:00:00Z',
  },
  {
    id: 'task_11',
    title: 'Advance Tax — Q2 FY 2025-26',
    description: 'Second installment advance tax computation and payment for Technovate Solutions.',
    clientId: 'cli_01',
    client: mockClients.find((c) => c.id === 'cli_01'),
    status: TaskStatus.TODO,
    priority: Priority.HIGH,
    financialYear: '2025-2026',
    dueDate: '2025-09-15T23:59:59Z',
    checklist: [
      { id: 'ti_task_11_1', taskId: 'task_11', label: 'Projected income estimated', isCompleted: false },
      { id: 'ti_task_11_2', taskId: 'task_11', label: 'Tax liability computed', isCompleted: false },
      { id: 'ti_task_11_3', taskId: 'task_11', label: 'Challan 280 paid', isCompleted: false },
    ],
    createdAt: '2025-08-20T10:00:00Z',
    updatedAt: '2025-08-20T10:00:00Z',
  },
  {
    id: 'task_12',
    title: 'GSTR-9 Annual Return — FY 2024-25',
    description: 'GST annual return for Kapoor Traders.',
    clientId: 'cli_04',
    client: mockClients.find((c) => c.id === 'cli_04'),
    assignedToId: 'usr_worker_03',
    assignedTo: mockUsers.find((u) => u.id === 'usr_worker_03'),
    status: TaskStatus.COMPLETED,
    priority: Priority.MEDIUM,
    financialYear: '2024-2025',
    dueDate: '2025-06-30T23:59:59Z',
    completedAt: '2025-06-25T12:00:00Z',
    checklist: makeChecklist(gstFilingChecklist, 'task_12', 7),
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2025-06-25T12:00:00Z',
  },
];

// ============================================================
// Activity Logs
// ============================================================

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log_01',
    taskId: 'task_01',
    userId: 'usr_worker_01',
    user: mockUsers.find((u) => u.id === 'usr_worker_01'),
    action: 'Started working on GSTR-3B for Technovate Solutions',
    createdAt: '2025-09-18T09:30:00Z',
  },
  {
    id: 'log_02',
    taskId: 'task_01',
    userId: 'usr_worker_01',
    user: mockUsers.find((u) => u.id === 'usr_worker_01'),
    action: 'Sales register reconciliation completed — ₹12.4L turnover verified',
    createdAt: '2025-09-19T14:00:00Z',
  },
  {
    id: 'log_03',
    taskId: 'task_01',
    userId: 'usr_worker_01',
    user: mockUsers.find((u) => u.id === 'usr_worker_01'),
    action: 'Difference of ₹14,200 found in 2B vs Purchase register. Followed up with client.',
    createdAt: '2025-09-22T11:00:00Z',
  },
  {
    id: 'log_04',
    taskId: 'task_02',
    userId: 'usr_worker_01',
    user: mockUsers.find((u) => u.id === 'usr_worker_01'),
    action: 'ITR-1 computation completed, submitted for Partner review',
    createdAt: '2025-09-20T16:00:00Z',
  },
  {
    id: 'log_05',
    taskId: 'task_03',
    userId: 'usr_worker_01',
    user: mockUsers.find((u) => u.id === 'usr_worker_01'),
    action: 'Trial balance received. Starting bank reconciliation.',
    createdAt: '2025-09-18T10:00:00Z',
  },
  {
    id: 'log_06',
    taskId: 'task_05',
    userId: 'usr_worker_03',
    user: mockUsers.find((u) => u.id === 'usr_worker_03'),
    action: 'Status changed to Waiting on Client — need vendor payment details for Q2',
    createdAt: '2025-09-18T09:00:00Z',
  },
  {
    id: 'log_07',
    taskId: 'task_07',
    userId: 'usr_worker_02',
    user: mockUsers.find((u) => u.id === 'usr_worker_02'),
    action: 'ITC reconciliation completed. Proceeding to liability computation.',
    createdAt: '2025-09-22T10:00:00Z',
  },
  {
    id: 'log_08',
    taskId: 'task_08',
    userId: 'usr_admin_01',
    user: mockUsers.find((u) => u.id === 'usr_admin_01'),
    action: 'Reviewed and approved. ITR-5 marked as Officially Filed.',
    createdAt: '2025-07-28T15:30:00Z',
  },
];

// ============================================================
// Documents
// ============================================================

export const mockDocuments: TaskDocument[] = [
  {
    id: 'doc_01',
    title: 'GSTR-3B Computation Sheet — Sep 2025',
    fileUrl: '/files/gstr3b-computation-sep25.xlsx',
    fileType: 'application/xlsx',
    clientId: 'cli_01',
    taskId: 'task_01',
    uploadedById: 'usr_worker_01',
    uploadedBy: mockUsers.find((u) => u.id === 'usr_worker_01'),
    isClientFacing: false,
    createdAt: '2025-09-22T14:30:00Z',
  },
  {
    id: 'doc_02',
    title: 'ITR-V Acknowledgment — AY 2025-26',
    fileUrl: '/files/itr-v-acknowledgment-ay2526.pdf',
    fileType: 'application/pdf',
    clientId: 'cli_03',
    taskId: 'task_02',
    uploadedById: 'usr_worker_01',
    uploadedBy: mockUsers.find((u) => u.id === 'usr_worker_01'),
    isClientFacing: true,
    createdAt: '2025-09-20T16:30:00Z',
  },
  {
    id: 'doc_03',
    title: 'Bank Statement — Apr-Jun 2025',
    fileUrl: '/files/bank-stmt-apr-jun-25.pdf',
    fileType: 'application/pdf',
    clientId: 'cli_01',
    taskId: 'task_01',
    uploadedById: 'usr_client_01',
    uploadedBy: mockUsers.find((u) => u.id === 'usr_client_01'),
    isClientFacing: true,
    createdAt: '2025-09-17T10:00:00Z',
  },
  {
    id: 'doc_04',
    title: 'Tax Audit Report (3CD) — FY 2024-25',
    fileUrl: '/files/tax-audit-3cd-fy2425.pdf',
    fileType: 'application/pdf',
    clientId: 'cli_05',
    taskId: 'task_03',
    uploadedById: 'usr_worker_01',
    uploadedBy: mockUsers.find((u) => u.id === 'usr_worker_01'),
    isClientFacing: false,
    createdAt: '2025-09-21T11:00:00Z',
  },
  {
    id: 'doc_05',
    title: 'GSTR-9 Filing Receipt — FY 2024-25',
    fileUrl: '/files/gstr9-receipt-fy2425.pdf',
    fileType: 'application/pdf',
    clientId: 'cli_04',
    taskId: 'task_12',
    uploadedById: 'usr_worker_03',
    uploadedBy: mockUsers.find((u) => u.id === 'usr_worker_03'),
    isClientFacing: true,
    createdAt: '2025-06-25T12:30:00Z',
  },
];

// ============================================================
// Client Document Requests
// ============================================================

export const mockDocumentRequests: DocumentRequest[] = [
  {
    id: 'dreq_01',
    clientId: 'cli_01',
    title: 'Upload October Bank Statement (PDF)',
    description: 'We need your current account bank statement for October 2025 for GST reconciliation.',
    isUploaded: false,
    requestedAt: '2025-09-22T15:00:00Z',
  },
  {
    id: 'dreq_02',
    clientId: 'cli_01',
    title: 'Upload Sales Register — Q2 FY 2025-26',
    description: 'Please share the sales register for July–September 2025 in Excel format.',
    isUploaded: true,
    uploadedFileUrl: '/files/sales-register-q2.xlsx',
    requestedAt: '2025-09-15T10:00:00Z',
    uploadedAt: '2025-09-17T10:00:00Z',
  },
  {
    id: 'dreq_03',
    clientId: 'cli_03',
    title: 'Upload Form 16 — FY 2024-25',
    description: 'Please upload your Form 16 received from your employer for income tax filing.',
    isUploaded: true,
    uploadedFileUrl: '/files/form16-fy2425.pdf',
    requestedAt: '2025-06-05T10:00:00Z',
    uploadedAt: '2025-06-10T10:00:00Z',
  },
  {
    id: 'dreq_04',
    clientId: 'cli_01',
    title: 'Upload Purchase Register — Sep 2025',
    description: 'Purchase register for September 2025 needed for GSTR-2B reconciliation.',
    isUploaded: false,
    requestedAt: '2025-09-20T10:00:00Z',
  },
];

// ============================================================
// Message Threads (Client Query Box)
// ============================================================

export const mockMessageThreads: MessageThread[] = [
  {
    id: 'thread_01',
    clientId: 'cli_01',
    subject: 'Query on GSTR-3B ITC Mismatch',
    messages: [
      {
        id: 'msg_01',
        threadId: 'thread_01',
        senderId: 'usr_worker_01',
        sender: mockUsers.find((u) => u.id === 'usr_worker_01'),
        senderRole: Role.WORKER,
        content: 'Hi Vikram, we found a difference of ₹14,200 between your 2B and purchase register for September. Could you check invoice #INV-2025-0847 from Reliance Digital?',
        createdAt: '2025-09-22T11:30:00Z',
      },
      {
        id: 'msg_02',
        threadId: 'thread_01',
        senderId: 'usr_client_01',
        sender: mockUsers.find((u) => u.id === 'usr_client_01'),
        senderRole: Role.CLIENT,
        content: 'Checking with our purchase team now. Will upload the corrected register by tomorrow.',
        createdAt: '2025-09-22T14:00:00Z',
      },
      {
        id: 'msg_03',
        threadId: 'thread_01',
        senderId: 'usr_worker_01',
        sender: mockUsers.find((u) => u.id === 'usr_worker_01'),
        senderRole: Role.WORKER,
        content: 'Perfect, thanks! Please upload through the Document Vault when ready.',
        createdAt: '2025-09-22T14:15:00Z',
      },
    ],
    createdAt: '2025-09-22T11:30:00Z',
    updatedAt: '2025-09-22T14:15:00Z',
  },
  {
    id: 'thread_02',
    clientId: 'cli_01',
    subject: 'Advance Tax Payment Reminder',
    messages: [
      {
        id: 'msg_04',
        threadId: 'thread_02',
        senderId: 'usr_admin_01',
        sender: mockUsers.find((u) => u.id === 'usr_admin_01'),
        senderRole: Role.ADMIN,
        content: 'Dear Vikram, this is a reminder that the Q2 advance tax installment (15th September) is approaching. Based on projected income, estimated liability is ₹2,85,000. Shall we proceed with challan generation?',
        createdAt: '2025-09-10T09:00:00Z',
      },
      {
        id: 'msg_05',
        threadId: 'thread_02',
        senderId: 'usr_client_01',
        sender: mockUsers.find((u) => u.id === 'usr_client_01'),
        senderRole: Role.CLIENT,
        content: 'Yes, please go ahead. We have sufficient funds in the current account.',
        createdAt: '2025-09-10T11:00:00Z',
      },
    ],
    createdAt: '2025-09-10T09:00:00Z',
    updatedAt: '2025-09-10T11:00:00Z',
  },
];

// ============================================================
// Dashboard Metrics
// ============================================================

export const mockDashboardMetrics: DashboardMetrics = {
  totalClients: mockClients.length,
  ongoingJobs: mockTasks.filter(
    (t) => t.status !== TaskStatus.COMPLETED
  ).length,
  pendingReviews: mockTasks.filter(
    (t) => t.status === TaskStatus.UNDER_REVIEW
  ).length,
  unassignedTasks: mockTasks.filter((t) => !t.assignedToId).length,
};

// ============================================================
// Compliance Calendar Deadlines
// ============================================================

export const mockComplianceDeadlines: ComplianceDeadline[] = [
  {
    id: 'cd_01',
    title: 'GSTR-1 Filing',
    dueDate: '2025-10-11T23:59:59Z',
    type: 'GST',
    description: 'Outward supply return for September 2025',
    isRecurring: true,
  },
  {
    id: 'cd_02',
    title: 'GSTR-3B Filing',
    dueDate: '2025-10-20T23:59:59Z',
    type: 'GST',
    description: 'Monthly summary return with tax payment for September 2025',
    isRecurring: true,
  },
  {
    id: 'cd_03',
    title: 'TDS Payment',
    dueDate: '2025-10-07T23:59:59Z',
    type: 'TDS',
    description: 'TDS deducted in September 2025 to be deposited',
    isRecurring: true,
  },
  {
    id: 'cd_04',
    title: 'Advance Tax — Q2 Installment',
    dueDate: '2025-09-15T23:59:59Z',
    type: 'ADVANCE_TAX',
    description: 'Second installment (45% of estimated annual liability)',
    isRecurring: false,
  },
  {
    id: 'cd_05',
    title: 'ITR Filing Deadline (Non-Audit)',
    dueDate: '2025-07-31T23:59:59Z',
    type: 'ITR',
    description: 'Individual and non-audit cases for AY 2025-26',
    isRecurring: false,
  },
  {
    id: 'cd_06',
    title: 'ITR Filing Deadline (Audit Cases)',
    dueDate: '2025-10-31T23:59:59Z',
    type: 'ITR',
    description: 'Companies and audit cases for AY 2025-26',
    isRecurring: false,
  },
  {
    id: 'cd_07',
    title: 'ROC Annual Return (MGT-7)',
    dueDate: '2025-11-29T23:59:59Z',
    type: 'ROC',
    description: 'Annual return filing within 60 days of AGM',
    isRecurring: false,
  },
  {
    id: 'cd_08',
    title: 'TDS Quarterly Return (Q2)',
    dueDate: '2025-10-31T23:59:59Z',
    type: 'TDS',
    description: 'Form 24Q/26Q for July–September 2025',
    isRecurring: false,
  },
];

// ============================================================
// Service Pages Data
// ============================================================

export const mockServicePages: ServicePage[] = [
  {
    slug: 'gst-compliance',
    title: 'GST Compliance & Returns',
    shortDescription: 'End-to-end GST registration, monthly/quarterly return filing, annual returns, and reconciliation services.',
    icon: 'Receipt',
    heroTitle: 'Seamless GST Compliance',
    heroSubtitle: 'From registration to annual returns — we handle every aspect of your GST obligations so you can focus on growing your business.',
    description: 'Our GST compliance services cover the complete lifecycle of Goods and Services Tax obligations. We ensure timely filing of GSTR-1, GSTR-3B, GSTR-9, and GSTR-9C with meticulous reconciliation of your purchase and sales registers against the GSTIN portal data. Our team proactively identifies ITC mismatches, resolves discrepancies with your vendors, and ensures zero-penalty compliance.',
    processSteps: [
      { title: 'Data Collection', description: 'We collect your sales and purchase registers, bank statements, and e-way bill data for the filing period.' },
      { title: 'Reconciliation', description: 'Our team reconciles your books with GSTR-2B auto-drafted data to identify and resolve any ITC mismatches.' },
      { title: 'Computation & Review', description: 'Tax liability is computed, reviewed by the CA partner, and shared with you for approval before filing.' },
      { title: 'Filing & Receipt', description: 'Returns are filed on the GST portal, challans are generated, and filing receipts are delivered to your document vault.' },
    ],
    faqs: [
      { question: 'What is the due date for GSTR-3B?', answer: 'GSTR-3B is due on the 20th of every month for businesses with turnover above ₹5 crore. For smaller businesses opting for the QRMP scheme, it is due quarterly.' },
      { question: 'What happens if GST returns are filed late?', answer: 'Late filing attracts interest at 18% per annum on the tax liability and a late fee of ₹50/day (₹20/day for nil returns), subject to maximum caps.' },
      { question: 'Do you handle GST audits?', answer: 'Yes. For businesses with turnover exceeding ₹5 crore, we prepare and file GSTR-9C (reconciliation statement) along with the annual return.' },
    ],
  },
  {
    slug: 'income-tax-filing',
    title: 'Income Tax Filing & Planning',
    shortDescription: 'Individual and business income tax returns, advance tax computation, and strategic tax planning.',
    icon: 'IndianRupee',
    heroTitle: 'Expert Income Tax Services',
    heroSubtitle: 'From salaried individuals to complex corporate returns — accurate filing, maximum deductions, and complete peace of mind.',
    description: 'We provide comprehensive income tax services for individuals, HUFs, partnership firms, LLPs, and companies. Our approach goes beyond mere compliance — we actively identify tax-saving opportunities under Sections 80C, 80D, 80G, and other provisions. For businesses, we handle advance tax computations, tax audit reports (Form 3CA/3CD), and transfer pricing documentation.',
    processSteps: [
      { title: 'Document Collection', description: 'We request Form 16, bank statements, investment proofs, capital gains statements, and other relevant documents through your secure portal.' },
      { title: 'Computation & Optimization', description: 'Our team prepares the tax computation, identifies deductions, and recommends the optimal tax regime (old vs. new).' },
      { title: 'Review & Approval', description: 'The computation is shared with you for review. Any queries are resolved through our messaging system.' },
      { title: 'Filing & Verification', description: 'ITR is filed on the Income Tax portal, and we assist with e-verification or ITR-V submission to CPC Bengaluru.' },
    ],
    faqs: [
      { question: 'Which ITR form should I file?', answer: 'It depends on your income sources — ITR-1 for salaried individuals, ITR-3 for business income, ITR-5 for partnerships, ITR-6 for companies. We select the correct form for you.' },
      { question: 'When is the ITR filing deadline?', answer: 'For individuals and non-audit cases: 31st July. For businesses requiring audit: 31st October. For transfer pricing cases: 30th November.' },
      { question: 'Do you help with tax notices?', answer: 'Yes. We handle responses to intimations under Section 143(1), scrutiny assessments, and demands from the Income Tax department.' },
    ],
  },
  {
    slug: 'statutory-audit',
    title: 'Statutory Audit & Assurance',
    shortDescription: 'Independent statutory audits, tax audits, internal audits, and assurance services for compliance and stakeholder confidence.',
    icon: 'ShieldCheck',
    heroTitle: 'Thorough Audit & Assurance',
    heroSubtitle: 'Independent, meticulous audits that build stakeholder confidence and ensure regulatory compliance.',
    description: 'Our audit practice provides independent assurance on your financial statements in compliance with the Companies Act, 2013 and applicable Accounting Standards (Ind AS / AS). We also conduct tax audits under Section 44AB, GST audits, internal audits, and special purpose audits. Our methodology combines substantive testing with analytical review to deliver actionable insights alongside compliance.',
    processSteps: [
      { title: 'Planning & Scoping', description: 'We assess your business operations, identify risk areas, and create a detailed audit plan with timelines.' },
      { title: 'Fieldwork & Testing', description: 'Our team reviews ledgers, vouches transactions, confirms balances, and tests internal controls.' },
      { title: 'Draft Report', description: 'Audit findings and management letter points are compiled into a draft report for your review and response.' },
      { title: 'Final Report & Filing', description: 'The signed audit report is issued and filed with regulators (MCA, Income Tax) as required.' },
    ],
    faqs: [
      { question: 'When is a statutory audit mandatory?', answer: 'For all companies registered under the Companies Act, 2013, regardless of turnover. For LLPs with turnover exceeding ₹40 lakh or contribution exceeding ₹25 lakh.' },
      { question: 'What is the difference between statutory and tax audit?', answer: 'Statutory audit verifies financial statements under the Companies Act. Tax audit (Section 44AB) is required for businesses with turnover exceeding ₹1 crore (₹10 crore if cash transactions are under 5%).' },
      { question: 'How long does an audit typically take?', answer: 'A standard statutory audit takes 2-4 weeks depending on the size and complexity of the entity. We plan timelines upfront to minimize disruption to your team.' },
    ],
  },
  {
    slug: 'company-incorporation',
    title: 'Company Incorporation & ROC',
    shortDescription: 'Private limited, LLP, and OPC incorporation, plus ongoing ROC compliance and annual filings.',
    icon: 'Building2',
    heroTitle: 'Company Formation & ROC Compliance',
    heroSubtitle: 'From choosing the right business structure to ongoing regulatory filings — we handle the paperwork so you can build your business.',
    description: 'We provide end-to-end company incorporation services including Private Limited Companies, Limited Liability Partnerships (LLPs), One Person Companies (OPCs), and Section 8 Companies. Post-incorporation, we handle all Ministry of Corporate Affairs (MCA) compliance including annual returns (MGT-7), financial statement filings (AOC-4), director KYC, charge registration, and changes in capital structure.',
    processSteps: [
      { title: 'Structure Advisory', description: 'We help you choose between Pvt Ltd, LLP, OPC, or Proprietorship based on your business goals, liability preferences, and tax implications.' },
      { title: 'Name Reservation & Filing', description: 'We reserve your company name via RUN/SPICe+ and file incorporation documents with the Registrar of Companies.' },
      { title: 'Post-Incorporation Setup', description: 'PAN, TAN, GST registration, bank account opening assistance, and initial board resolutions are handled by our team.' },
      { title: 'Ongoing ROC Compliance', description: 'We manage annual filings (MGT-7, AOC-4), director appointments/resignations, share transfers, and other MCA filings throughout the year.' },
    ],
    faqs: [
      { question: 'How long does it take to incorporate a Pvt Ltd company?', answer: 'With the SPICe+ form, incorporation typically takes 5-7 working days from the date of filing, including PAN and TAN allotment.' },
      { question: 'What is the minimum requirement for a Pvt Ltd company?', answer: 'Minimum 2 directors (at least 1 resident in India), 2 shareholders, ₹1 lakh authorized share capital, and a registered office address.' },
      { question: 'What are the annual compliance requirements?', answer: 'Annual return (MGT-7) within 60 days of AGM, financial statements (AOC-4) within 30 days of AGM, director KYC (DIR-3 KYC) by 30th September, and income tax return by 31st October.' },
    ],
  },
];

// ============================================================
// Testimonials
// ============================================================

export const mockTestimonials = [
  {
    id: 'test_01',
    name: 'Vikram Singh',
    company: 'Technovate Solutions Pvt. Ltd.',
    role: 'Managing Director',
    quote: 'Sharma & Associates has been instrumental in keeping our GST and tax compliance on track. Their proactive approach to deadlines and transparent communication through the client portal has saved us countless hours.',
    rating: 5,
  },
  {
    id: 'test_02',
    name: 'Ananya Reddy',
    company: 'GreenLabel Organics LLP',
    role: 'Partner',
    quote: 'As a growing LLP, we needed a CA firm that understands both compliance and business strategy. The team at Sharma & Associates delivers on both fronts — their audit insights helped us streamline our financial processes.',
    rating: 5,
  },
  {
    id: 'test_03',
    name: 'Deepak Joshi',
    company: 'Horizon Infra Projects Pvt. Ltd.',
    role: 'CEO',
    quote: 'What sets Sharma & Associates apart is their attention to detail. During our statutory audit, they identified discrepancies that our internal team had missed. Highly professional and reliable.',
    rating: 5,
  },
];
